### ISSUE TITLE
How far will this project go? wrt to OpenAI Gym

### ISSUE THREAD

**Issue by GeorgeS2019** [ChengYen-Tang/RL.Algorithm#1]
[OpenAI Gym for c#](https://github.com/SciSharp/Gym.NET)

Feel free to use the 3D environment [here ](https://github.com/JimFFM/ml-hackathon-2021)to further develop RL for .NET

**Comment by ChengYen-Tang** [comment]
I have observed Gym.NET for a long time, this project has not been maintained for a long time

**Comment by ChengYen-Tang** [comment]
I'm also developing slowly because the dependency library doesn't 100% implement the API it needs. It takes a long time to request and communicate.
The nature of programming languages is also a big challenge
